// asaoffice pixel icons: the emoji used as icons in the office (buttons, labels, cards) are swapped for 16×16 pixel art in the office's own palette,
// drawn here as text and turned into images when the page loads. Any element you add that contains one of the mapped emoji gets the pixel icon
// instead (a MutationObserver does it), so the add-ons can keep writing "📮" in their texts. Tooltips, text boxes, code and the answers of the
// agents keep the real emoji. `?pixelIcons=off` brings the emoji back (remembered). `__asaoffice.icon('mail')` makes one icon element.
(() => {
  'use strict';
  const ns = window.__asaoffice;
  const on = ns.setting('pixelIcons', ['on', 'off'], 'on') === 'on';

  // . = empty. Outline K is the office's dark brown.
  const PAL = {
    K: '#3a2117', B: '#744122', b: '#b9814a', t: '#e6c98a', c: '#fff6dc', R: '#c8503c', r: '#8f2f26', M: '#e98ca0', m: '#c9667f', O: '#e8902e', Y: '#f4cf4e', y: '#fdeea6',
    G: '#4f9a45', g: '#98cf62', D: '#2a6a33', U: '#4a86d8', u: '#a7cbf2', N: '#27478a', P: '#7a4fb8', p: '#bda0e0', W: '#ffffff', s: '#d9d9e0', S: '#a3a3ae', A: '#5a5a68',
  };

  const ART = {
    mail: [
      '................',
      '................',
      '....KKKKKKKK....',
      '...KRRRRRRRRK...',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KRRKKKKKKRRK..',
      '..KRRRRRRRRRRK..',
      '..KrRRRRRRRRrK..',
      '..KrrrrrrrrrrK..',
      '...KKKKKKKKKK...',
      '......KBBK......',
      '......KBBK......',
      '....KKKBBKKK....',
      '................',
      '................',
    ],
    books: [
      '................',
      '................',
      '...KKKKKKKKKK...',
      '..KUUUUUUUUUcK..',
      '..KUuuuuuuuUcK..',
      '..KKKKKKKKKKKK..',
      '.KRRRRRRRRRRRcK.',
      '.KRMMMMMMMMRRcK.',
      '.KKKKKKKKKKKKKK.',
      '..KGGGGGGGGGGcK.',
      '..KGggggggggGcK.',
      '..KKKKKKKKKKKKK.',
      '................',
      '................',
      '................',
      '................',
    ],
    bulb: [
      '................',
      '.....KKKKKK.....',
      '....KyyYYYYK....',
      '...KyyYYYYYYK...',
      '...KyYYYYYYYK...',
      '...KyYYYYYYYK...',
      '...KYYYYYYYOK...',
      '...KYYYYYYYOK...',
      '....KYYYYYOK....',
      '.....KYYYOK.....',
      '.....KsSsSK.....',
      '.....KAAAAK.....',
      '.....KsSsSK.....',
      '......KKKK......',
      '................',
      '................',
    ],
    moon: [
      '................',
      '......KKKK......',
      '....KKyyYK......',
      '...KyyYYK.......',
      '..KyyYYK........',
      '..KyYYK.........',
      '.KyYYYK.........',
      '.KyYYYK.........',
      '.KyYYYK.........',
      '.KyYYYYK....KK..',
      '..KYYYYYKKKKYK..',
      '..KYYYYYYYYYK...',
      '...KOYYYYYYK....',
      '....KKOOOKK.....',
      '......KKK.......',
      '................',
    ],
    bag: [
      '................',
      '......KKKK......',
      '.....KtttK......',
      '......KttK......',
      '.....KKKKKK.....',
      '..KKbbbbbbbbKK..',
      '.KbbbbbbKbbbbbK.',
      '.KbbbbbKKKbbbbK.',
      '.KbbbbKbKbbbbbK.',
      '.KbbbbbKKKbbbbK.',
      '.KbbbbbbKbKbbbK.',
      '.KbbbbbKKKbbbbK.',
      '.KbbbbbbKbbbbbK.',
      '..KbbbbbbbbbbK..',
      '...KKbbbbbbKK...',
      '.....KKKKKK.....',
    ],
    clock: [
      '................',
      '..KKK......KKK..',
      '.KRRRK....KRRRK.',
      '.KRRKKKKKKKKRRK.',
      '..KKKcccccccKK..',
      '...KcccccccccK..',
      '..KccccKccccccK.',
      '..KccccKccccccK.',
      '..KccccKKKKcccK.',
      '..KcccccccccccK.',
      '..KcccccccccccK.',
      '...KcccccccccK..',
      '...KKcccccccKK..',
      '..KK.KKKKKK.KK..',
      '.KK..........KK.',
      '................',
    ],
    broom: [
      '..............KK',
      '.............KBK',
      '............KBK.',
      '...........KBK..',
      '..........KBK...',
      '.........KBK....',
      '........KKK.....',
      '.......KYYYK....',
      '......KYOYYYK...',
      '.....KYYOYYYK...',
      '....KYYOYYYYK...',
      '...KYOYYOYYK....',
      '..KYYOYYYYK.....',
      '..KKYYYYKK......',
      '....KKKK........',
      '................',
    ],
    bell: [
      '................',
      '.......KK.......',
      '......KYYK......',
      '.....KYYYYK.....',
      '....KYyYYYYK....',
      '....KYyYYYYK....',
      '...KYyYYYYYYK...',
      '...KYYYYYYYOK...',
      '..KYYYYYYYYOOK..',
      '..KYYYYYYYYOOK..',
      '.KYYYYYYYYYYOOK.',
      '.KKKKKKKKKKKKKK.',
      '......KOOK......',
      '.......KK.......',
      '................',
      '................',
    ],
    bellOff: [
      '................',
      '.......KK...R...',
      '......KsSK.RR...',
      '.....KsSSSKRR...',
      '....KsSSSSRRK...',
      '....KsSSSRRSK...',
      '...KsSSSRRSSSK..',
      '...KSSSRRSSSAK..',
      '..KSSSRRSSSSAAK.',
      '..KSSRRSSSSSAAK.',
      '.KSSRRSSSSSSSAAK',
      '.KKKRKKKKKKKKKK.',
      '.....RKAAK......',
      '.....R.KK.......',
      '................',
      '................',
    ],
    archive: [
      '................',
      '................',
      '..KKKKKKKKKKKK..',
      '..KSSSSSSSSSSK..',
      '..KKKKKKKKKKKK..',
      '..KsssKKKKsssK..',
      '..KsssKYYKsssK..',
      '..KsssKKKKsssK..',
      '..KKKKKKKKKKKK..',
      '..KsssKKKKsssK..',
      '..KsssKYYKsssK..',
      '..KsssKKKKsssK..',
      '..KKKKKKKKKKKK..',
      '..KAAAAAAAAAAK..',
      '..KKKKKKKKKKKK..',
      '................',
    ],
    check: [
      '................',
      '................',
      '.............KK.',
      '............KGGK',
      '...........KGggK',
      '..........KGggK.',
      '.KK......KGggK..',
      'KGGK....KGggK...',
      'KGggK..KGggK....',
      '.KGggKKGggK.....',
      '..KGggGggK......',
      '...KGggGK.......',
      '....KGGK........',
      '.....KK.........',
      '................',
      '................',
    ],
    stop: [
      '................',
      '.....KKKKKK.....',
      '...KKRRRRRRKK...',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '.KRRRRRRRRRRRRK.',
      '.KRWWWWWWWWWWRK.',
      '.KRWWWWWWWWWWRK.',
      '.KRRRRRRRRRRRRK.',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '...KKRRRRRRKK...',
      '.....KKKKKK.....',
      '................',
      '................',
      '................',
    ],
    lock: [
      '................',
      '.....KKKKKK.....',
      '....KSssssSK....',
      '....KS....SK....',
      '....KS....SK....',
      '...KKKKKKKKKK...',
      '..KYYYYYYYYYYK..',
      '..KYOOOOOOOOYK..',
      '..KYOOOKKOOOYK..',
      '..KYOOOKKOOOYK..',
      '..KYOOOOKOOOYK..',
      '..KYOOOOOOOOYK..',
      '..KOOOOOOOOOOK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
    note: [
      '................',
      '..KKKKKKKKKK....',
      '..KcccccccccK.KK',
      '..KcKKKKKKKcKBBK',
      '..KcccccccccKBBK',
      '..KcKKKKKKKcKBK.',
      '..KcccccccccKK..',
      '..KcKKKKKKcYKK..',
      '..KcccccccKYYK..',
      '..KcKKKKKcYYYK..',
      '..KcccccccKYK...',
      '..KKKKKKKKKK....',
      '................',
      '................',
      '................',
      '................',
    ],
    folder: [
      '................',
      '................',
      '..KKKKKK........',
      '..KYYYYYKKKKKK..',
      '..KYyyyyYYYYYYK.',
      '..KKKKKKKKKKKKK.',
      '..KYYYYYYYYYYYK.',
      '..KYyyyyyyyyyYK.',
      '..KYYYYYYYYYYYK.',
      '..KYYYYYYYYYYOK.',
      '..KYYYYYYYYYOOK.',
      '..KOOOOOOOOOOOK.',
      '..KKKKKKKKKKKKK.',
      '................',
      '................',
      '................',
    ],
    clipboard: [
      '................',
      '......KKKK......',
      '..KKKKSSSSKKKK..',
      '..KbbKKssKKbbK..',
      '..KbKKKKKKKKbK..',
      '..KbKcccccccKK..',
      '..KbKcKKKKKcK...',
      '..KbKcccccccK...',
      '..KbKcKKKKccK...',
      '..KbKcccccccK...',
      '..KbKcKKKKKcK...',
      '..KbKcccccccK...',
      '..KbKKKKKKKKK...',
      '..KKKKKKKKKK....',
      '................',
      '................',
    ],
    pencil: [
      '..............KK',
      '............KRRK',
      '...........KRRRK',
      '..........KRRRK.',
      '.........KYYYK..',
      '........KYYYK...',
      '.......KYYYK....',
      '......KYYYK.....',
      '.....KYYYK......',
      '....KYYYK.......',
      '...KYYYK........',
      '..KtYYK.........',
      '.KtttK..........',
      '.KKKK...........',
      '................',
      '................',
    ],
    trash: [
      '................',
      '......KKKK......',
      '..KKKKSSSSKKKK..',
      '..KSSSSSSSSSSK..',
      '..KKKKKKKKKKKK..',
      '...KsSsSsSsSK...',
      '...KsSsSsSsSK...',
      '...KsSsSsSsSK...',
      '...KsSsSsSsSK...',
      '...KsSsSsSsSK...',
      '...KsSsSsSsSK...',
      '...KsSsSsSsSK...',
      '....KsSsSsSK....',
      '....KKKKKKKK....',
      '................',
      '................',
    ],
    envelope: [
      '................',
      '................',
      '................',
      '..KKKKKKKKKKKK..',
      '..KcKcccccccKcK.',
      '..KccKccccccKcK.',
      '..KcccKcccKccK..',
      '..KccccKKKcccK..',
      '..KcccKcccKccK..',
      '..KccKcccccKcK..',
      '..KcKccccccKcK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
      '................',
    ],
    brain: [
      '................',
      '....KKKK.KKK....',
      '...KMMMMKMMMK...',
      '..KMMmMMMMmMMK..',
      '.KMMMMMKMMMMMMK.',
      '.KMmMMMKMMMmMMK.',
      '.KMMMMMKMMMMMMK.',
      '.KMMmMMMKMMmMMK.',
      '.KMMMMMKMMMMMMK.',
      '..KMMMMKMMMMMK..',
      '...KMMMMMMMMK...',
      '....KKMMMMKK....',
      '......KKKK......',
      '................',
      '................',
      '................',
    ],
    eyes: [
      '................',
      '................',
      '..KKKK..KKKK....',
      '.KWWWWK.KWWWWK..',
      'KWWUUWWKWWUUWWK.',
      'KWWUKWWKWWUKWWK.',
      'KWWUUWWKWWUUWWK.',
      '.KWWWWK.KWWWWK..',
      '..KKKK..KKKK....',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    bolt: [
      '................',
      '.......KKKK.....',
      '......KYYYK.....',
      '.....KYYYK......',
      '....KYYYK.......',
      '...KYYYYYYK.....',
      '...KKKKYYK......',
      '......KYYK......',
      '.....KYYK.......',
      '.....KYK........',
      '....KYK.........',
      '....KK..........',
      '................',
      '................',
      '................',
      '................',
    ],
    leaf: [
      '................',
      '................',
      '..........KKKK..',
      '.......KKKGGGGK.',
      '.....KKGGGGgGGK.',
      '....KGGGGGGgGGK.',
      '...KGGGGGGgGGGK.',
      '..KGGGGGGgGGGK..',
      '..KGGGGGgGGGK...',
      '.KGGGGGgGGGK....',
      'KDKGGGgGGKK.....',
      'KDDKGgGKK.......',
      '.KDDKKK.........',
      '..KDK...........',
      '................',
      '................',
    ],
    speech: [
      '................',
      '................',
      '..KKKKKKKKKKKK..',
      '.KcccccccccccK..',
      '.KcKKcKKcKKccK..',
      '.KcccccccccccK..',
      '.KcKKcKKcKKccK..',
      '.KcccccccccccK..',
      '..KKKKKKKKKKKK..',
      '....KcK.........',
      '....KK..........',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    tomato: [
      '................',
      '......KGGK......',
      '....KKGGGGKK....',
      '...KGGKGGKGGK...',
      '..KKKRRKKRRKKK..',
      '.KRRRRRRRRRRRRK.',
      '.KRWWRRRRRRRRRK.',
      '.KRWRRRRRRRRRRK.',
      '.KRRRRRRRRRRRRK.',
      '.KRRRRRRRRRRRRK.',
      '..KrRRRRRRRRrK..',
      '..KrrRRRRRRrrK..',
      '...KKrrrrrrKK...',
      '.....KKKKKK.....',
      '................',
      '................',
    ],
    undo: [
      '................',
      '................',
      '....KK..........',
      '...KUUK.........',
      '..KUUUUKKKKKK...',
      '.KUUUUUUUUUUUK..',
      '.KUUUUUUUUUUUUK.',
      '..KUUUUKKKKUUUK.',
      '...KUUK....KUUK.',
      '....KK.....KUUK.',
      '...........KUUK.',
      '..........KUUUK.',
      '.........KUUUK..',
      '.........KKKK...',
      '................',
      '................',
    ],
    person: [
      '................',
      '.....KKKKKK.....',
      '....KBBBBBBK....',
      '....KBtttBBK....',
      '....KtKttKtK....',
      '....KttttttK....',
      '.....KKttKK.....',
      '....KUUUUUUK....',
      '...KUUUUUUUUK...',
      '...KtUUUUUUtK...',
      '...KKUUUUUUKK...',
      '.....KBBBBK.....',
      '.....KBKKBK.....',
      '.....KKK.KKK....',
      '................',
      '................',
    ],
    robot: [
      '................',
      '.......KK.......',
      '.......KR.......',
      '....KKKKKKKK....',
      '...KssssssssK...',
      '...KsUUssUUsK...',
      '..KKsUWssUWsKK..',
      '..KSsssssssSSK..',
      '..KKsKKKKKKsKK..',
      '...KsssssssssK..',
      '....KKKKKKKK....',
      '...KsssssssK....',
      '...KsSSSSSsK....',
      '...KKKKKKKKK....',
      '................',
      '................',
    ],
    trophy: [
      '................',
      '..KKKKKKKKKKKK..',
      '.KYKYYYYYYYYKYK.',
      '.KYKYyYYYYYYKYK.',
      '.KYKYyYYYYYYKYK.',
      '..KKYyYYYYYYKK..',
      '....KYyYYYYYK...',
      '.....KYYYYYK....',
      '......KYYYK.....',
      '.......KYK......',
      '.......KYK......',
      '......KOOOK.....',
      '.....KOOOOOK....',
      '.....KKKKKKK....',
      '................',
      '................',
    ],
    inbox: [
      '................',
      '................',
      '......KKKK......',
      '......KUUK......',
      '......KUUK......',
      '....KKKUUKKK....',
      '.....KKUUKK.....',
      '......KUUK......',
      '.KKKK..KK..KKKK.',
      '.KSSKKKKKKKKSSK.',
      '.KSSSSSSSSSSSSK.',
      '.KSsssssssssSSK.',
      '.KKKKKKKKKKKKKK.',
      '................',
      '................',
      '................',
    ],
    clip: [
      '................',
      '.....KKKKK......',
      '....KSsssSK.....',
      '....KSKKKsK.....',
      '....KSKsKsK.....',
      '....KSKsKsK.....',
      '....KSKsKsK.....',
      '....KSKsKsK.....',
      '....KSKsKsK.....',
      '....KSKsKSK.....',
      '....KSKsKSK.....',
      '....KSKKKSK.....',
      '....KSsssSK.....',
      '.....KKKKK......',
      '................',
      '................',
    ],
    merge: [
      '................',
      '................',
      '.KKK........KKK.',
      '.KGGK......KGGK.',
      '.KGGK......KGGK.',
      '..KGGK....KGGK..',
      '...KGGK..KGGK...',
      '....KGGKKGGK....',
      '.....KGGGGK.....',
      '......KGGK......',
      '......KGGK......',
      '.....KGGGGK.....',
      '.....KKKKKK.....',
      '................',
      '................',
      '................',
    ],
    square: [
      '................',
      '................',
      '...KKKKKKKKKK...',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KRRRRRRRRRRK..',
      '..KrrrrrrrrrrK..',
      '...KKKKKKKKKK...',
      '................',
      '................',
      '................',
      '................',
    ],
    send: [
      '................',
      '................',
      '..K.............',
      '..KKK...........',
      '..KccKKK........',
      '..KcccccKKK.....',
      '..KcccccccccKK..',
      '..KcccccccccccKK',
      '..KSsssssssssKK.',
      '..KSSssssssKK...',
      '..KSSSsssKK.....',
      '..KSSKKKK.......',
      '..KSK...........',
      '..KK............',
      '................',
      '................',
    ],
    coffee: [
      '................',
      '.....s..s.......',
      '......s..s......',
      '................',
      '..KKKKKKKKKK....',
      '..KcccccccccKKK.',
      '..KBBBBBBBBcK.K.',
      '..KcccccccccK.K.',
      '..KcccccccccKKK.',
      '...KcccccccK....',
      '...KscccccsK....',
      '....KKKKKKK.....',
      '..KKKKKKKKKKKK..',
      '..KSSSSSSSSSSK..',
      '...KKKKKKKKKK...',
      '................',
    ],
    cross: [
      '................',
      '................',
      '..KK........KK..',
      '.KRRK......KRRK.',
      '..KRRK....KRRK..',
      '...KRRK..KRRK...',
      '....KRRKKRRK....',
      '.....KRRRRK.....',
      '.....KRRRRK.....',
      '....KRRKKRRK....',
      '...KRRK..KRRK...',
      '..KRRK....KRRK..',
      '.KRRK......KRRK.',
      '..KK........KK..',
      '................',
      '................',
    ],
    hourglass: [
      '................',
      '...KKKKKKKKKK...',
      '...KBBBBBBBBK...',
      '....KuuuuuuK....',
      '.....KuYYuK.....',
      '......KYYK......',
      '.......KK.......',
      '.......KK.......',
      '......KuuK......',
      '.....KuuuuK.....',
      '....KuuYYuuK....',
      '...KuYYYYYYuK...',
      '...KBBBBBBBBK...',
      '...KKKKKKKKKK...',
      '................',
      '................',
    ],
    fire: [
      '................',
      '.......K........',
      '......KRK.......',
      '.....KRRK...K...',
      '....KRROK..KRK..',
      '...KRROOKKKRRK..',
      '...KRROYOKRROK..',
      '..KRROYYYOROOK..',
      '..KROYYYYYOOOK..',
      '..KROYYyYYYOOK..',
      '..KROYyyyYYOOK..',
      '..KRROYyyYYOK...',
      '...KRROYYYOK....',
      '....KKROOOK.....',
      '.....KKKKK......',
      '................',
    ],
    scroll: [
      '................',
      '..KKKKKKKKKKK...',
      '.KtttttttttttK..',
      '.KtKKKKKKKKKtK..',
      '..KcccccccccK...',
      '..KcKKKKKKKcK...',
      '..KcccccccccK...',
      '..KcKKKKKKcK....',
      '..KcccccccccK...',
      '..KcKKKKKKKcK...',
      '..KcccccccccK...',
      '.KtKKKKKKKKKtK..',
      '.KtttttttttttK..',
      '..KKKKKKKKKKK...',
      '................',
      '................',
    ],
    sun: [
      '................',
      '.......K........',
      '...K...K...K....',
      '....K..K..K.....',
      '.....KKKKK......',
      '..KK.KYYYK.KK...',
      '.....KYyYYK.....',
      'KKKK.KYYYYK.KKKK',
      '.....KYYYOK.....',
      '..KK.KYYOOK.KK..',
      '.....KKKKK......',
      '....K..K..K.....',
      '...K...K...K....',
      '.......K........',
      '................',
      '................',
    ],
    sunflower: [
      '................',
      '.....KK.KK......',
      '....KYYKYYK.....',
      '..KKKYYYYYKKK...',
      '.KYYYKBBBKYYYK..',
      '.KYYKBBbBBKYYK..',
      '.KYYKBbBbBKYYK..',
      '.KYYKBBbBBKYYK..',
      '.KYYYKBBBKYYYK..',
      '..KKKYYYYYKKK...',
      '....KYYKYYK.....',
      '.....KKKGK......',
      '.......KGK......',
      '......KGGGK.....',
      '.....KGKGKGK....',
      '................',
    ],
    people: [
      '................',
      '..KKKK....KKKK..',
      '.KBBBBK..KBBBBK.',
      '.KBttBK..KBttBK.',
      '.KttttK..KttttK.',
      '..KKKK....KKKK..',
      '.KUUUUK..KRRRRK.',
      'KUUUUUUKKRRRRRRK',
      'KtUUUUtKKtRRRRtK',
      '.KUUUUK..KRRRRK.',
      '.KUKKUK..KRKKRK.',
      '.KKK.KK..KKK.KK.',
      '................',
      '................',
      '................',
      '................',
    ],
    warning: [
      '................',
      '.......KK.......',
      '......KYYK......',
      '.....KYYYYK.....',
      '.....KYKKYK.....',
      '....KYYKKYYK....',
      '....KYYKKYYK....',
      '...KYYYKKYYYK...',
      '...KYYYKKYYYK...',
      '..KYYYYYYYYYYK..',
      '..KYYYYKKYYYYK..',
      '.KYYYYYKKYYYYYK.',
      '.KKKKKKKKKKKKKK.',
      '................',
      '................',
      '................',
    ],
    house: [
      '................',
      '.......KK.......',
      '......KRRK......',
      '.....KRRRRK.....',
      '....KRRRRRRK....',
      '...KRRRRRRRRK...',
      '..KRRRRRRRRRRK..',
      '.KRRRRRRRRRRRRK.',
      '.KKKKKKKKKKKKKK.',
      '..KttttttttttK..',
      '..KtUUttKKKttK..',
      '..KtUUttKbKttK..',
      '..KttttttKKKtK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
    page: [
      '................',
      '..KKKKKKKKK.....',
      '..KcccccccKK....',
      '..KcKKKKKcKcK...',
      '..KcccccccKKKK..',
      '..KcKKKKKKKccK..',
      '..KcccccccccsK..',
      '..KcKKKKKKKccK..',
      '..KcccccccccsK..',
      '..KcKKKKcccccK..',
      '..KcccccccccsK..',
      '..KcKKKKKKcccK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
    ],
    mushroom: [
      '................',
      '.....KKKKKK.....',
      '...KKRRRRRRKK...',
      '..KRRWWRRRRRRK..',
      '.KRRWWWRRRWWRRK.',
      '.KRRRWRRRRWWRRK.',
      '.KRRRRRRRRRRRRK.',
      '.KKKKKKKKKKKKKK.',
      '....KcccccK.....',
      '....KcctccK.....',
      '....KcctccK.....',
      '....KctttcK.....',
      '.....KKKKK......',
      '................',
      '................',
      '................',
    ],
    pickaxe: [
      '................',
      '....KKKKKK......',
      '..KKSSSSSSKK....',
      '.KSsssKKsssSK...',
      'KSssK..KBKssSK..',
      'KSK...KBK.KSK...',
      'KK...KBK..KSK...',
      '.....KBK..KK....',
      '....KBK.........',
      '...KBK..........',
      '..KBK...........',
      '..KBK...........',
      '...KK...........',
      '................',
      '................',
      '................',
    ],
    fishing: [
      '..............KK',
      '.............KBK',
      '............KBK.',
      '...........KBK..',
      '..........KBK.K.',
      '.........KBK..K.',
      '........KBK...K.',
      '.......KBK....K.',
      '......KBK.....K.',
      '.....KBK......K.',
      '....KBK.......K.',
      '...KBK......KKK.',
      '..KKK......KK.K.',
      '...........KKKK.',
      '................',
      '................',
    ],
    swords: [
      '................',
      'KK..........KK..',
      'KSK........KSK..',
      '.KSK......KSK...',
      '..KSK....KSK....',
      '...KSK..KSK.....',
      '....KSKKSK......',
      '.....KSSK.......',
      '....KKSSKK......',
      '...KBKKKKBK.....',
      '..KBK.KK.KBK....',
      '.KKK..KK..KKK...',
      '................',
      '................',
      '................',
      '................',
    ],
    receipt: [
      '................',
      '..KKKKKKKKKK....',
      '..KcccccccccK...',
      '..KcKKKKKKcK....',
      '..KcccccccccK...',
      '..KcKKKKKccK....',
      '..KcccccccccK...',
      '..KcKKKKKKcK....',
      '..KcccccccccK...',
      '..KcKKKcccccK...',
      '..KcccccccccK...',
      '..KcKcKcKcKcK...',
      '..KKKKKKKKKKK...',
      '................',
      '................',
      '................',
    ],
    star: [
      '................',
      '.......KK.......',
      '......KYYK......',
      '......KYYK......',
      '.....KYyYYK.....',
      'KKKKKKYyYYKKKKK.',
      '.KYYYYYYYYYYYK..',
      '..KYYYyYYYYYK...',
      '...KYYYYYYYK....',
      '...KYYYYYYYK....',
      '..KYYYKKYYYYK...',
      '..KYYK..KYYK....',
      '.KYYK....KYYK...',
      '.KKK......KKK...',
      '................',
      '................',
    ],
    box: [
      '................',
      '................',
      '...KKKKKKKKKK...',
      '..KbbbbKKbbbbK..',
      '.KbbbbbKKbbbbbK.',
      '.KKKKKKKKKKKKKK.',
      '.KbbbbbKKbbbbbK.',
      '.KbbbbbKKbbbbbK.',
      '.KbbbbbKKbbbbbK.',
      '.KbbbbbKKbbbbbK.',
      '.KbbbbbKKbbbbbK.',
      '.KBBBBBKKBBBBBK.',
      '.KKKKKKKKKKKKKK.',
      '................',
      '................',
      '................',
    ],
    snow: [
      '................',
      '.......KK.......',
      '...KK..KK..KK...',
      '....KuuKKuuK....',
      '.....KuKKuK.....',
      '.KK...KuuK...KK.',
      '..KuKKKuuKKKuK..',
      '...KuuuuuuuuK...',
      '...KuuuuuuuuK...',
      '..KuKKKuuKKKuK..',
      '.KK...KuuK...KK.',
      '.....KuKKuK.....',
      '....KuuKKuuK....',
      '...KK..KK..KK...',
      '.......KK.......',
      '................',
    ],
    autumn: [
      '................',
      '.........KK.....',
      '.......KKOOK....',
      '.....KKOOOOOK...',
      '....KOORROOOK...',
      '...KOORROOOOK...',
      '..KOORROOOORK...',
      '..KORROOOORRK...',
      '..KRROOOORRK....',
      '...KROOORRK.....',
      '....KKRRKK......',
      '....KBKKK.......',
      '...KBK..........',
      '..KK............',
      '................',
      '................',
    ],
    sprout: [
      '................',
      '................',
      '...KKKK..KKKK...',
      '..KGGGGKKGGGGK..',
      '.KGgggGKKGgggGK.',
      '.KGgggGKKGgggGK.',
      '..KGGGKKKKGGGK..',
      '...KKK.KK.KKK...',
      '.......KK.......',
      '.......KGK......',
      '.......KGK......',
      '.....KKKGKKK....',
      '....KBBBBBBBK...',
      '.....KBBBBBK....',
      '......KKKKK.....',
      '................',
    ],
    sparkle: [
      '................',
      '.......K........',
      '......KYK.......',
      '......KYK.......',
      '.....KYyYK......',
      '..KKKKYyYKKKK...',
      '.KYYYYyyyYYYYK..',
      '..KKKKYyYKKKK...',
      '.....KYyYK......',
      '......KYK...KK..',
      '......KYK..KYK..',
      '.......K...KYK..',
      '............K...',
      '................',
      '................',
      '................',
    ],
    calendar: [
      '................',
      '..KKKKKKKKKKKK..',
      '..KRRRRRRRRRRK..',
      '..KRKRRRRRRKRK..',
      '..KKKKKKKKKKKK..',
      '..KcccccccccsK..',
      '..KcKKcKKcKKcK..',
      '..KcccccccccsK..',
      '..KcKKcKKcKKcK..',
      '..KcccccccccsK..',
      '..KcKKcKKcRRcK..',
      '..KcccccccRRsK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
    ],
    gear: [
      '................',
      '.......KK.......',
      '....KK.KK.KK....',
      '...KSSKSSKSSK...',
      '....KSSSSSSK....',
      '..KKSSsssSSKK...',
      '.KSSSsKKKsSSSK..',
      'KSSSSsK..KsSSSSK',
      '.KSSSsKKKsSSSK..',
      '..KKSSsssSSKK...',
      '....KSSSSSSK....',
      '...KSSKSSKSSK...',
      '....KK.KK.KK....',
      '.......KK.......',
      '................',
      '................',
    ],
    tree: [
      '................',
      '.....KKKKKK.....',
      '...KKGGGGGGKK...',
      '..KGGGgGGGGGGK..',
      '.KGGgggGGGGGGGK.',
      '.KGGgGGGGGGDGGK.',
      '.KGGGGGGGGDDGGK.',
      '..KGGGGGGDDDGK..',
      '..KKGGGGGGGGKK..',
      '....KKKBBKKK....',
      '......KBBK......',
      '......KBBK......',
      '.....KKBBKK.....',
      '................',
      '................',
      '................',
    ],
    unlock: [
      '................',
      '....KKKKKK......',
      '...KSssssSK.....',
      '...KS....SK.....',
      '...KS....SK.....',
      '...KS...........',
      '..KKKKKKKKKK....',
      '.KYYYYYYYYYYK...',
      '.KYOOOOOOOOYK...',
      '.KYOOOKKOOOYK...',
      '.KYOOOKKOOOYK...',
      '.KYOOOOKOOOYK...',
      '.KOOOOOOOOOOK...',
      '.KKKKKKKKKKKK...',
      '................',
      '................',
    ],
    pause: [
      '................',
      '................',
      '..KKKKK..KKKKK..',
      '..KUUUK..KUUUK..',
      '..KUuuK..KUuuK..',
      '..KUUUK..KUUUK..',
      '..KUUUK..KUUUK..',
      '..KUUUK..KUUUK..',
      '..KUUUK..KUUUK..',
      '..KUUUK..KUUUK..',
      '..KUUUK..KUUUK..',
      '..KNNNK..KNNNK..',
      '..KKKKK..KKKKK..',
      '................',
      '................',
      '................',
    ],
    checkOff: [
      '................',
      '................',
      '................',
      '...KKKKKKKKKK...',
      '...KccccccccK...',
      '...KccccccccK...',
      '...KccccccccK...',
      '...KccccccccK...',
      '...KccccccccK...',
      '...KccccccccK...',
      '...KccccccccK...',
      '...KKKKKKKKKK...',
      '................',
      '................',
      '................',
      '................',
    ],
    checkOn: [
      '................',
      '................',
      '................',
      '...KKKKKKKKKK...',
      '...KccccccccK.K.',
      '...KcccccccKGK..',
      '...KcccccKKGKK..',
      '...KKcccKGGKcK..',
      '...KGKcKGGKccK..',
      '...KGGKGGKcccK..',
      '...KcKGGKccccK..',
      '...KKKKKKKKKK...',
      '................',
      '................',
      '................',
      '................',
    ],
    bookmark: [
      '................',
      '................',
      '....KKKKKKKK....',
      '....KRRRRRRK....',
      '....KRRRRRRK....',
      '....KRRRRRRK....',
      '....KRRRRRRK....',
      '....KRRRRRRK....',
      '....KRRRRRRK....',
      '....KRRKKRRK....',
      '....KRK..KRK....',
      '....KK....KK....',
      '................',
      '................',
      '................',
      '................',
    ],
    frame: [
      '................',
      '..KKKKKKKKKKKK..',
      '..KbbbbbbbbbbK..',
      '..KbKKKKKKKKbK..',
      '..KbKuuuuuuKbK..',
      '..KbKuuuWuuKbK..',
      '..KbKuuuuuuKbK..',
      '..KbKuGuuGuKbK..',
      '..KbKGGGGGGKbK..',
      '..KbKKKKKKKKbK..',
      '..KbbbbbbbbbbK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
      '................',
      '................',
    ],
    compass: [
      '................',
      '.....KKKKKK.....',
      '...KKccccccKK...',
      '..KccccRcccccK..',
      '.KcccccRRccccK..',
      '.KccccRRRRcccK..',
      '.KcccKKKKKKccK..',
      '.KccUUUUKKcccK..',
      '.KcccUUUUccccK..',
      '..KccccUUcccK...',
      '...KKccUccKK....',
      '.....KKKKKK.....',
      '................',
      '................',
      '................',
      '................',
    ],
    wheat: [
      '................',
      '.......K........',
      '......KYK..K....',
      '.....KYYK.KYK...',
      '......KYYKYYK...',
      '.....KYYKYYK....',
      '......KYKYK.....',
      '.....KYYKYYK....',
      '......KYYKK.....',
      '.......KYK......',
      '.......KGK......',
      '.......KGK......',
      '......KGK.......',
      '......KK........',
      '................',
      '................',
    ],
    menu: [
      '................',
      '................',
      '................',
      '..KKKKKKKKKKKK..',
      '..KBBBBBBBBBBK..',
      '..KKKKKKKKKKKK..',
      '................',
      '..KKKKKKKKKKKK..',
      '..KBBBBBBBBBBK..',
      '..KKKKKKKKKKKK..',
      '................',
      '..KKKKKKKKKKKK..',
      '..KBBBBBBBBBBK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
  };

  // emoji → icon (the variation selector U+FE0F is optional)
  const EMOJI = {
    '📮': 'mail', '📚': 'books', '💡': 'bulb', '🌙': 'moon', '💰': 'bag', '⏰': 'clock', '🧹': 'broom', '🔔': 'bell', '🔕': 'bellOff', '🗄': 'archive',
    '✅': 'check', '⛔': 'stop', '🔒': 'lock', '🔐': 'lock', '📝': 'note', '📁': 'folder', '📋': 'clipboard', '✏': 'pencil', '🗑': 'trash', '✉': 'envelope',
    '🧠': 'brain', '👀': 'eyes', '⚡': 'bolt', '🌿': 'leaf', '🗣': 'speech', '🍅': 'tomato', '↩': 'undo', '👤': 'person', '🤖': 'robot', '🏆': 'trophy',
    '📥': 'inbox', '📎': 'clip', '🔀': 'merge', '⏹': 'square', '➤': 'send',
    '☕': 'coffee', '❌': 'cross', '⏳': 'hourglass', '🔥': 'fire', '📜': 'scroll', '☀': 'sun', '🌻': 'sunflower', '👥': 'people', '⚠': 'warning', '🏠': 'house',
    '📂': 'folder', '🗂': 'folder', '💬': 'speech', '📄': 'page', '🍄': 'mushroom', '⛏': 'pickaxe', '🎣': 'fishing', '⚔': 'swords', '🧾': 'receipt', '⭐': 'star',
    '📦': 'box', '❄': 'snow', '🍂': 'autumn', '🌱': 'sprout', '✨': 'sparkle', '📅': 'calendar', '⚙': 'gear', '🕒': 'clock', '☐': 'checkOff', '☑': 'checkOn',
    '🌳': 'tree', '🔓': 'unlock', '⏸': 'pause', '🔖': 'bookmark', '🖼': 'frame', '🧭': 'compass', '🌾': 'wheat', '✓': 'check', '☰': 'menu',
  };

  if (!on) { ns.icon = (name) => document.createTextNode(Object.keys(EMOJI).find((k) => EMOJI[k] === name) ?? ''); return; }

  // Draw every icon once into a data URL and give each its own class.
  const urls = {};
  for (const [name, rows] of Object.entries(ART)) {
    const cv = document.createElement('canvas');
    cv.width = 16;
    cv.height = 16;
    const c = cv.getContext('2d');
    rows.forEach((row, y) => { for (let x = 0; x < 16; x++) { const col = PAL[row[x]]; if (col) { c.fillStyle = col; c.fillRect(x, y, 1, 1); } } });
    urls[name] = cv.toDataURL('image/png');
  }
  const style = document.createElement('style');
  style.textContent = `.pxi { display: inline-block; width: 1.2em; height: 1.2em; vertical-align: -0.25em; background-size: 100% 100%; background-repeat: no-repeat; image-rendering: pixelated; }\n`
    + Object.entries(urls).map(([n, u]) => `.pxi-${n} { background-image: url(${u}); }`).join('\n');
  document.head.appendChild(style);

  ns.icon = (name) => { const i = document.createElement('i'); i.className = `pxi pxi-${name}`; i.setAttribute('aria-hidden', 'true'); return i; };

  // Swap the emoji in text for icons, anywhere in the page except where real text belongs (inputs, code, the agents' answers, our own icons).
  const RE = new RegExp(`(${Object.keys(EMOJI).map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\uFE0F?`, 'g');
  const SKIP = 'textarea, input, select, option, script, style, pre, code, .pxi, .asa-b-text, .asa-md, .asa-msg, [contenteditable], canvas';
  function convert(node) {
    if (node.nodeType === Node.TEXT_NODE) {
      const parent = node.parentElement;
      if (!parent || parent.closest(SKIP) || !RE.test(node.nodeValue)) { RE.lastIndex = 0; return; }
      RE.lastIndex = 0;
      const frag = document.createDocumentFragment();
      let last = 0;
      const text = node.nodeValue;
      for (const m of text.matchAll(RE)) {
        if (m.index > last) frag.append(text.slice(last, m.index));
        frag.append(ns.icon(EMOJI[m[1]]));
        last = m.index + m[0].length;
      }
      if (last < text.length) frag.append(text.slice(last));
      node.replaceWith(frag);
    } else if (node.nodeType === Node.ELEMENT_NODE && !node.matches?.(SKIP)) {
      const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
      const texts = [];
      for (let t = walker.nextNode(); t; t = walker.nextNode()) texts.push(t);
      for (const t of texts) convert(t);
    }
  }
  let queue = new Set();
  let scheduled = false;
  const flush = () => {
    scheduled = false;
    const todo = [...queue];
    queue = new Set();
    for (const n of todo) if (n.isConnected) convert(n);
  };
  const start = () => {
    new MutationObserver((muts) => {
      for (const m of muts) {
        if (m.type === 'characterData') queue.add(m.target);
        else for (const n of m.addedNodes) queue.add(n);
      }
      if (!scheduled) { scheduled = true; requestAnimationFrame(flush); }
    }).observe(document.body, { childList: true, subtree: true, characterData: true });
    convert(document.body);
  };
  if (document.body) start(); else addEventListener('DOMContentLoaded', start, { once: true }); // the add-ons load in <head>, before the page body exists

  /** Every icon at once, big, for a look: __asaoffice.iconSheet() (call again to close). */
  ns.iconSheet = () => {
    const old = document.getElementById('asa-icon-sheet');
    if (old) { old.remove(); return; }
    const box = document.createElement('div');
    box.id = 'asa-icon-sheet';
    box.style.cssText = 'position:fixed;inset:20px;z-index:99999;background:#fff6dc;border:3px solid #744122;padding:12px;overflow:auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:10px;font:12px sans-serif;color:#3a2117';
    for (const name of Object.keys(ART)) {
      const cell = document.createElement('div');
      cell.style.cssText = 'text-align:center';
      const i = ns.icon(name);
      i.style.cssText = 'width:64px;height:64px;vertical-align:baseline;display:block;margin:0 auto 4px';
      const real = Object.keys(EMOJI).filter((k) => EMOJI[k] === name).join(' ');
      cell.append(i, document.createTextNode(`${name} ${real}`));
      box.append(cell);
    }
    document.body.append(box);
  };
})();
