// Builds "Asa Office.app" in ~/Applications: a one-click way to open the office without Terminal.
//   npm run app              build/replace the app (drag it to the Dock afterwards)
//   npm run app -- --remove  stop the office it started and delete the app
// The app is a stay-open AppleScript applet that runs `node tools/app.mjs open` on launch and when its
// Dock icon is clicked, and `node tools/app.mjs stop` when you quit it. It has a fixed bundle id and a
// Calendar usage string, so macOS asks once for Calendar access on behalf of "Asa Office".
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { PNG } from 'pngjs';

import { Sprite, hex } from './lib/pixel.mjs';

if (process.platform !== 'darwin') {
  console.error('The Asa Office app is macOS-only. Use `npm run office` instead.');
  process.exit(1);
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const appDir = process.env.ASAOFFICE_APP_DIR || path.join(os.homedir(), 'Applications');
const app = path.join(appDir, 'Asa Office.app');
const BUNDLE_ID = 'dev.asaoffice.app';
const run = (cmd, args) => execFileSync(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] }).toString();

if (process.argv.includes('--remove')) {
  try { run(process.execPath, [path.join(root, 'tools', 'app.mjs'), 'stop']); } catch { /* not running */ }
  fs.rmSync(app, { recursive: true, force: true });
  console.log(`Removed ${app}`);
  process.exit(0);
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'asaoffice-app-'));

// ── Icon: villager Asa in a little window of sky and floorboards, scaled up as pixel art ──
function iconMaster() {
  const N = 36;
  const s = new Sprite(N, N);
  const [x0, y0, x1, y1] = [3, 3, 32, 32]; // inclusive box with 1px-cut corners
  for (let y = y0; y <= y1; y++)
    for (let x = x0; x <= x1; x++) {
      const cx = x === x0 || x === x1;
      const cy = y === y0 || y === y1;
      if (cx && cy) continue; // cut corner
      const nearCorner = (x === x0 + 1 || x === x1 - 1) && (y === y0 + 1 || y === y1 - 1);
      const edge = cx || cy || nearCorner;
      const floor = y >= 22;
      const plank = (x + (y % 2) * 3) % 6 === 0;
      s.set(x, y, hex(edge ? '#744122' : floor ? (plank ? '#9c5d2f' : '#c07f43') : y < 12 ? '#8fd0e8' : '#a8dcef'));
    }
  for (const [x, y] of [[8, 7], [9, 7], [26, 9], [27, 9]]) s.set(x, y, hex('#fff6dc')); // clouds
  // Standing, facing-down frame of the first villager (frame 1 of the down row).
  const sheet = Sprite.load(path.join(root, 'overlay', 'characters', 'char_0.png')); // villager 1, Asa
  const frame = new Sprite(16, 32);
  for (let y = 0; y < 32; y++) for (let x = 0; x < 16; x++) frame.set(x, y, sheet.get(16 + x, y));
  s.blit(frame, 10, 2);
  // Scale ×28 into a 1024×1024 PNG with an 8px transparent margin.
  const scale = 28;
  const png = new PNG({ width: 1024, height: 1024 });
  for (let y = 0; y < N * scale; y++)
    for (let x = 0; x < N * scale; x++) {
      const c = s.get(Math.floor(x / scale), Math.floor(y / scale));
      if (!c) continue;
      const i = ((y + 8) * 1024 + (x + 8)) * 4;
      png.data[i] = c[0];
      png.data[i + 1] = c[1];
      png.data[i + 2] = c[2];
      png.data[i + 3] = c[3];
    }
  const file = path.join(tmp, 'icon-1024.png');
  fs.writeFileSync(file, PNG.sync.write(png));
  return file;
}

function buildIcns(master) {
  const set = path.join(tmp, 'AsaOffice.iconset');
  fs.mkdirSync(set);
  for (const size of [16, 32, 128, 256, 512]) {
    for (const [mult, suffix] of [[1, ''], [2, '@2x']]) {
      const px = size * mult;
      run('sips', ['-z', String(px), String(px), master, '--out', path.join(set, `icon_${size}x${size}${suffix}.png`)]);
    }
  }
  const icns = path.join(tmp, 'applet.icns');
  run('iconutil', ['-c', 'icns', set, '-o', icns]);
  return icns;
}

// ── Applet ──
const q = (s) => `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
const node = process.execPath;
const appScript = path.join(root, 'tools', 'app.mjs');
const source = `-- Asa Office: opens the pixel office, starting it in the background if needed. Generated by tools/install-app.mjs.
property nodePath : ${q(node)}
property appScript : ${q(appScript)}

on run
	openOffice()
end run

on reopen
	openOffice()
end reopen

on openOffice()
	try
		do shell script quoted form of nodePath & " " & quoted form of appScript & " open"
	on error errMsg
		display dialog "Asa Office tidak bisa dibuka:" & return & return & errMsg buttons {"OK"} default button 1 with title "Asa Office" with icon caution
	end try
end openOffice

on quit
	try
		do shell script quoted form of nodePath & " " & quoted form of appScript & " stop"
	end try
	continue quit
end quit
`;
const scriptFile = path.join(tmp, 'AsaOffice.applescript');
fs.writeFileSync(scriptFile, source);

fs.mkdirSync(appDir, { recursive: true });
fs.rmSync(app, { recursive: true, force: true });
run('osacompile', ['-s', '-o', app, scriptFile]);

fs.copyFileSync(buildIcns(iconMaster()), path.join(app, 'Contents', 'Resources', 'applet.icns'));
fs.rmSync(path.join(app, 'Contents', 'Resources', 'Assets.car'), { force: true }); // else it overrides applet.icns

const plist = path.join(app, 'Contents', 'Info.plist');
const setKey = (key, value) => {
  try { run('/usr/libexec/PlistBuddy', ['-c', `Delete :${key}`, plist]); } catch { /* absent */ }
  run('/usr/libexec/PlistBuddy', ['-c', `Add :${key} string ${value}`, plist]);
};
setKey('CFBundleIdentifier', BUNDLE_ID);
setKey('CFBundleName', 'Asa Office');
setKey('CFBundleDisplayName', 'Asa Office');
const why = 'Asa Office shows your calendar events on the wall calendar in the pixel office.';
setKey('NSCalendarsFullAccessUsageDescription', why);
setKey('NSCalendarsUsageDescription', why);
run('codesign', ['--force', '--deep', '-s', '-', app]);
run('touch', [app]);

fs.rmSync(tmp, { recursive: true, force: true });
console.log(`Built ${app}`);
console.log('Open it from Finder (Go → Home → Applications) or Spotlight, then right-click its Dock icon → Options → Keep in Dock.');
console.log('Quit it (⌘Q) to stop the office it started.');
